reviews:
  auto_review: true
  review_status: true

language:
  javascript:
    enabled: true
  typescript:
    enabled: true

checks:
  security: true
  performance: true
  correctness: true
  best_practices: true

comments:
  style: concise
  tone: professional

paths:
  include:
    - app/**
    - lib/**
    - components/**
  exclude:
    - node_modules/**
    - .next/**
    - dist/**
